---
- name: 布署支付密码集群
  hosts: nodes
  gather_facts: no

  tasks:
      - name: "stop server"
        shell: /ssx10/bin/nvpcmd stop {{ node_id }}
        ignore_errors: True
        async: 5
        poll: 5

      - name: "stop server"
        shell: rm -f /ssx10/data/*


