---
      - name: "copy to the remote server"
        copy:
            src: ssx10
            dest: /
            backup: yes
        register: run_log
      - debug: var=run_log

      - name: "chmod +x "
        file:
            path: /ssx10/bin/nvpcmd
            mode: 0775
      - name: "make link"
        file:
            src: /ssx10/bin/nvpcmd
            dest: /etc/init.d/nvpcmd
            state: link

      - name: "copy conf file"
        template: src=nvpcmd.j2 dest=/ssx10/conf/nvpcmd.json

      - name: "copy conf file"
        template: src=node.j2 dest=/ssx10/conf/node.json

      - name: "stop server"
        shell: /ssx10/bin/nvpcmd stop {{ node_id }}

      - name: "start server"
        shell: /ssx10/bin/nvpcmd start {{ node_id }}
        register: run_log
      - debug: var=run_log
